import { DeploymentConfig, PackageDeployment } from "../types/deployment";
import { NetworkType } from "./network";
import devnetDeploymentsJson from "../../deployments-processed/_all-packages-devnet.json";
import testnetDeploymentsJson from "../../deployments-processed/_all-packages-testnet.json";
import mainnetDeploymentsJson from "../../deployments-processed/_all-packages-mainnet.json";
import localnetDeploymentsJson from "../../deployments-processed/_all-packages-localnet.json";

/**
 * Bundled deployment configs
 *
 * Each network has its own deployment file: _all-packages-{network}.json
 * These are generated by: ./packages/scripts/deploy_verified.sh --network <network>
 *
 * Directory structure:
 *   packages/deployments/{network}/   - raw deployment JSONs per package
 *   sdk/deployments-processed/        - processed _all-packages-{network}.json files
 *
 * To deploy to a new network:
 * 1. Deploy contracts: ./packages/scripts/deploy_verified.sh --network testnet
 * 2. Rebuild SDK: npm run build
 */

function deploymentFileName(network: string): string {
    return `_all-packages-${network}.json`;
}

type NodeFsModule = {
    existsSync(path: string): boolean;
    readFileSync(path: string, encoding: BufferEncoding): string;
};

type NodePathModule = {
    resolve(...paths: string[]): string;
};

function isNodeRuntime(): boolean {
    return typeof process !== "undefined" && Boolean(process.versions?.node);
}

function getEnv(name: string): string | undefined {
    if (!isNodeRuntime()) return undefined;
    return process.env?.[name];
}

function getCwd(): string | undefined {
    if (!isNodeRuntime() || typeof process.cwd !== "function") return undefined;
    try {
        return process.cwd();
    } catch {
        return undefined;
    }
}

function loadNodeModule<T>(moduleName: string): T | undefined {
    if (!isNodeRuntime()) return undefined;
    try {
        const req = Function("return typeof require !== 'undefined' ? require : undefined")() as
            | NodeRequire
            | undefined;
        return req?.(moduleName) as T | undefined;
    } catch {
        return undefined;
    }
}

function resolvePath(...parts: string[]): string {
    const path = loadNodeModule<NodePathModule>("node:path");
    return path?.resolve(...parts) ?? parts.filter(Boolean).join("/");
}

function deploymentSearchDirs(): string[] {
    const cwd = getCwd();
    const dirs: Array<string | undefined> = [
        getEnv("GOVEX_SDK_DEPLOYMENTS_DIR"),
        getEnv("GOVEX_DEPLOYMENTS_DIR"),
    ];

    if (cwd) {
        dirs.push(
            resolvePath(cwd, "sdk/deployments-processed"),
            resolvePath(cwd, "../sdk/deployments-processed"),
            resolvePath(cwd, "../../sdk/deployments-processed"),
            resolvePath(cwd, "deployments-processed"),
        );
    }

    if (isNodeRuntime() && typeof __dirname !== "undefined") {
        dirs.push(
            // Source/tsx path: sdk/src/config -> sdk/deployments-processed
            resolvePath(__dirname, "../../deployments-processed"),
            // Built CJS path: sdk/dist/cjs/config -> sdk/deployments-processed
            resolvePath(__dirname, "../../../deployments-processed"),
        );
    }

    return dirs.filter((dir): dir is string => Boolean(dir));
}

function tryReadRuntimeDeployments(network: string): DeploymentConfig | undefined {
    const fs = loadNodeModule<NodeFsModule>("node:fs");
    if (!fs) return undefined;

    const filename = deploymentFileName(network);

    for (const dir of deploymentSearchDirs()) {
        const file = resolvePath(dir, filename);
        if (!fs.existsSync(file)) {
            continue;
        }

        try {
            return JSON.parse(fs.readFileSync(file, "utf8")) as DeploymentConfig;
        } catch {
            return undefined;
        }
    }

    return undefined;
}

// Runtime files are checked first so localnet deployments generated after build
// are not hidden by deployment JSON that was bundled into dist at build time.
const bundledDeployments: Partial<Record<NetworkType, DeploymentConfig>> = {
    devnet: devnetDeploymentsJson as DeploymentConfig,
    testnet: testnetDeploymentsJson as DeploymentConfig,
    mainnet: mainnetDeploymentsJson as DeploymentConfig,
    localnet: localnetDeploymentsJson as DeploymentConfig,
};

/**
 * Get bundled deployments for a network
 * @param network - The network type
 * @returns DeploymentConfig for the network, or undefined if not available
 */
export function getBundledDeployments(network: NetworkType | string): DeploymentConfig | undefined {
    if (network === "mainnet" || network === "testnet" || network === "devnet" || network === "localnet") {
        return tryReadRuntimeDeployments(network) ?? bundledDeployments[network];
    }
    // Custom RPC URLs don't have bundled deployments
    return undefined;
}

/**
 * Deployment configuration manager
 * Loads and provides access to package deployment data
 */
export class DeploymentManager {
    private deployments: DeploymentConfig;

    constructor(deployments: DeploymentConfig) {
        this.deployments = deployments;
    }

    /**
     * Create DeploymentManager from deployment config object
     */
    static fromConfig(config: DeploymentConfig): DeploymentManager {
        return new DeploymentManager(config);
    }

    /**
     * Get deployment info for a specific package
     */
    getPackage(packageName: string): PackageDeployment | undefined {
        return this.deployments[packageName];
    }

    /**
     * Get package ID for a specific package
     */
    getPackageId(packageName: string): string | undefined {
        return this.deployments[packageName]?.packageId;
    }

    /**
     * Get all shared objects across all packages
     */
    getAllSharedObjects() {
        const shared: Array<{ package: string; object: any }> = [];
        for (const [pkg, deployment] of Object.entries(this.deployments)) {
            deployment.sharedObjects.forEach((obj) => {
                shared.push({ package: pkg, object: obj });
            });
        }
        return shared;
    }

    /**
     * Get all admin caps across all packages
     */
    getAllAdminCaps() {
        const caps: Array<{ package: string; cap: any }> = [];
        for (const [pkg, deployment] of Object.entries(this.deployments)) {
            deployment.adminCaps.forEach((cap) => {
                caps.push({ package: pkg, cap });
            });
        }
        return caps;
    }

    /**
     * Get Factory shared object from futarchy_factory package
     */
    getFactory() {
        const factory = this.getPackage("futarchy_factory");
        return factory?.sharedObjects.find(obj => obj.name === "Factory");
    }

    /**
     * Get PackageRegistry from AccountProtocol
     */
    getPackageRegistry() {
        const protocol = this.getPackage("AccountProtocol");
        return protocol?.sharedObjects.find(obj => obj.name === "PackageRegistry");
    }

    /**
     * Get PackageAdminCap from AccountProtocol
     * This cap controls package registry management
     */
    getPackageAdminCap() {
        const protocol = this.getPackage("AccountProtocol");
        return protocol?.adminCaps.find(cap => cap.name === "PackageAdminCap");
    }

    /**
     * Get FeeAdminCap from futarchy_markets_core
     *
     * IMPORTANT: This cap must be transferred to the protocol DAO account and registered
     * as a managed asset with key "protocol:fee_admin_cap" for governance actions to work.
     *
     * @returns FeeAdminCap object info or undefined if not found
     */
    getFeeAdminCap() {
        const marketsCore = this.getPackage("futarchy_markets_core");
        return marketsCore?.adminCaps.find(cap => cap.name === "FeeAdminCap");
    }

    /**
     * Get all package IDs as a map
     */
    getAllPackageIds(): Record<string, string> {
        const packageIds: Record<string, string> = {};
        for (const [name, deployment] of Object.entries(this.deployments)) {
            packageIds[name] = deployment.packageId;
        }
        return packageIds;
    }
}
